apiVersion: v1
kind: Pod
metadata:
    name: nginx-redis-mysql 
    labels: 
     env: dev 
spec:
    containers:
     - name: samplepod-con1
       image: nginx 
       ports: 
          - containerPort: 80

     - name: con2
       image: redis 
       ports:
          - containerPort: 6379

     - name: con3
       image: mysql
       ports:
          - containerPort: 3306
       env:
         - name: MYSQL_ROOT_PASSWORD
           value: "sbs123"

                   
